apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/emailservice
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: environment-configmap  
              key: EMAIL_SERVICE_PORT
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice-service
spec:
  selector:
    app: emailservice
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 8080