apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: mohamed1780/paymentservice:latest
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: environment-configmap
              key: PAYMENT_SERVICE_PORT
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice-service
spec:
  selector:
    app: paymentservice
  type: ClusterIP
  ports:
  - port: 50052 
    targetPort: 50051