apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogueservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogueservice
  template:
    metadata:
      labels:
        app: productcatalogueservice
    spec:
      containers:
      - name: productcatalogueservice
        image: mohamed1780/productcatalog:latest
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: environment-configmap  
              key: PRODUCT_CATALOG_SERVICE_PORT
        ports:
        - containerPort: 3550
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogueservice-service
spec:
  selector:
    app: productcatalogueservice
  type: ClusterIP
  ports:
  - port: 3550
    targetPort: 3550