apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: recommendationservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/recommendationservice
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: environment-configmap
              key: RECOMMANTATION_SERVICE_PORT
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: environment-configmap  
              key: PRODUCT_CATALOG_SERVICE_ADDR
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice-service
spec:
  selector:
    app: recommendationservice
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080