apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/adservice
      ports:
      - containerPort: 9555
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/cartservice
        env:
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: cartservice-configmap  
              key: ASPNETCORE_URLS
        ports:
        - containerPort: 7070
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/checkoutservice
        env:
        - name: GRPC_HEALTH_PROBE_VERSION
          valueFrom:
            configMapKeyRef:
              name: checkoutservice-configmap  
              key: GRPC_HEALTH_PROBE_VERSION
        - name: GOTRACEBACK
          valueFrom:
            configMapKeyRef:
              name: checkoutservice-configmap  
              key: GOTRACEBACK
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: checkoutservice-configmap  
              key: PRODUCT_CATALOG_SERVICE_ADDR
        - name: SHIPPING_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: checkoutservice-configmap  
              key: SHIPPING_SERVICE_ADDR
        - name: CART_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: checkoutservice-configmap  
              key: CART_SERVICE_ADDR
        - name: CURRENCY_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: checkoutservice-configmap  
              key: CURRENCY_SERVICE_ADDR
        - name: EMAIL_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: checkoutservice-configmap  
              key: EMAIL_SERVICE_ADDR
        - name: PAYMENT_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: checkoutservice-configmap  
              key: PAYMENT_SERVICE_ADDR
        ports:
        - containerPort: 5050
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/currencyservice
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: currencyservice-configmap  
              key: PORT
      ports:
      - containerPort: 7000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/emailservice
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: emailservice-configmap  
              key: PORT
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/frontend
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap  
              key: PRODUCT_CATALOG_SERVICE_ADDR
        - name: SHIPPING_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap  
              key: SHIPPING_SERVICE_ADDR
        - name: CART_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap  
              key: CART_SERVICE_ADDR
        - name: CURRENCY_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap  
              key: CURRENCY_SERVICE_ADDR
        - name: CHECKOUT_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap  
              key: CHECKOUT_SERVICE_ADDR
        - name: RECOMMENDATION_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap  
              key: RECOMMENDATION_SERVICE_ADDR
        - name: AD_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap  
              key: AD_SERVICE_ADDR
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap  
              key: PORT
      ports:
      - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/loadgenerator
        env:
        - name: FRONTEND_ADDR
          valueFrom:
            configMapKeyRef:
              name: loadgenerator-configmap  
              key: FRONTEND_ADDR
        ports:
        - containerPort: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/paymentservice
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: paymentservice-configmap  
              key: PORT
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogueservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogueservice
  template:
    metadata:
      labels:
        app: productcatalogueservice
    spec:
      containers:
      - name: productcatalogueservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/productcatalogservice
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: productcatalogueservice-configmap  
              key: PORT
        ports:
        - containerPort: 3550
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: recommendationservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/recommendationservice
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: recommendationservice-configmap  
              key: PORT
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: recommendationservice-configmap  
              key: PRODUCT_CATALOG_SERVICE_ADDR
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: https://github.com/marcbal/win-server-project/tree/main/projet-fil-rouge-neosoft/shippingservice
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: shippingservice-configmap  
              key: PORT
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---




