apiVersion: v1
kind: ConfigMap
metadata:
  name: cartservice-configmap
data:
  ASPNETCORE_URLS: http://*:7070
  REDIS_ADDR: redis:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkoutservice-configmap
data:
  GRPC_HEALTH_PROBE_VERSION: v0.3.6
  GOTRACEBACK: single
  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
  SHIPPING_SERVICE_ADDR: shippingservice:50051
  CART_SERVICE_ADDR: cartservice:7070
  CURRENCY_SERVICE_ADDR: currencyservice:7000
  EMAIL_SERVICE_ADDR: emailservice:5000
  PAYMENT_SERVICE_ADDR: paymentservice:50052
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emailservice-configmap
data:
  GRPC_HEALTH_PROBE_VERSION: v0.3.6
  GOTRACEBACK: single
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: currencyservice-configmap
data:
  PORT: 7000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emailservice-configmap
data:
  PORT: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
  SHIPPING_SERVICE_ADDR: shippingservice:50051
  CART_SERVICE_ADDR: cartservice:7070
  CURRENCY_SERVICE_ADDR: currencyservice:7000
  CHECKOUT_SERVICE_ADDR: checkoutservice:5050
  RECOMMENDATION_SERVICE_ADDR: recommendationservice:8080
  AD_SERVICE_ADDR: adservice:9555
  PORT: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loadgenerator-configmap
data:
  FRONTEND_ADDR: frontend:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paymentservice-configmap
data:
  PORT: 50051
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: productcatalogservice-configmap
data:
  PORT: 3550
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendationservice-configmap
data:
  PORT: 8080
  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shippingservice-configmap
data:
  PORT: 50051
