apiVersion: v1
kind: Service
metadata:
  name: adservice-service
spec:
  selector:
    app: adservice
  type: ClusterIP
  ports:
  - port: 9555  
    targetPort: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice-service
spec:
  selector:
    app: cartservice
  type: ClusterIP
  ports:
  - port: 7070
    targetPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice-service
spec:
  selector:
    app: checkoutservice
  type: ClusterIP
  ports:
  - port: 5050
    targetPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice-service
spec:
  selector:
    app: currencyservice
  type: ClusterIP
  ports:
  - port: 7000
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice-service
spec:
  selector:
    app: emailservice
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator-service
spec:
  selector:
    app: loadgenerator
  type: ClusterIP
  ports:
  - port: 
    targetPort: 
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice-service
spec:
  selector:
    app: paymentservice
  type: ClusterIP
  ports:
  - port: 50051 
    targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogueservice-service
spec:
  selector:
    app: productcatalogueservice
  type: ClusterIP
  ports:
  - port: 3550
    targetPort: 3550
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice-service
spec:
  selector:
    app: recommendationservice
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice-service
spec:
  selector:
    app: shippingservice
  type: ClusterIP
  ports:
  - port: 50051 
    targetPort: 50051
---



