---
# tasks file for docker

- name: Download Docker script
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: "+x"
- name: Install Docker
  ansible.builtin.command: sh /tmp/get-docker.sh
  changed_when: true
- name: Ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started